### ISSUE TITLE
Zebra-look for table

### ISSUE THREAD

**Issue by vogella** [OpenReqEU/eclipse-plugin-vogella#26]
Would be nice to have iterating row colors. In combination with #25 that would be nice.

@SimonScholz can you have a look?

**Comment by SimonScholz** [comment]
![image](https://user-images.githubusercontent.com/7559962/56265315-7fd7b400-60e9-11e9-8397-57f31d0a7d3f.png)
Does this look good to you?

**Comment by jnerlich** [comment]
Ver good. Thanks
-------- Ursprüngliche Nachricht --------Von: Simon Scholz <notifications@github.com> Datum: 17.04.19  08:19  (GMT+01:00) An: OpenReqEU/eclipse-plugin-vogella <eclipse-plugin-vogella@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [OpenReqEU/eclipse-plugin-vogella] Zebra-look for table (#26) 
Does this look good to you?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenReqEU/eclipse-plugin-vogella","title":"OpenReqEU/eclipse-plugin-vogella","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenReqEU/eclipse-plugin-vogella"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SimonScholz in #26: ![image](https://user-images.githubusercontent.com/7559962/56265315-7fd7b400-60e9-11e9-8397-57f31d0a7d3f.png)\r\nDoes this look good to you?"}],"action":{"name":"View Issue","url":"https://github.com/OpenReqEU/eclipse-plugin-vogella/issues/26#issuecomment-483952536"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OpenReqEU/eclipse-plugin-vogella/issues/26#issuecomment-483952536",
"url": "https://github.com/OpenReqEU/eclipse-plugin-vogella/issues/26#issuecomment-483952536",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
